%ifndef WIN32_MAC_RENAMING_MAC
%define WIN32_MAC_RENAMING_MAC

;==============================================================================
; Defines renaming macros for importing C functions and data to assembly
; MSVC
;==============================================================================

%macro CFUNCEXTERN 1
extern _%1
%define %1 _%1
%endmacro

%macro CDATAEXTERN 1
extern _%1
%define %1 _%1
%endmacro

%endif


