#ifndef VERSIONINFO_H
#define VERSIONINFO_H

#define FELLOWVERSION        "WinFellow v0.5.6 r$WCREV$ (Git-$WCBRANCH$-$WCCOMMITSHORT$)"
#define FELLOWLONGVERSION    "WinFellow Amiga Emulator v0.5.6.$WCREV$ (Git-$WCBRANCH$-$WCCOMMITSHORT$)" 
#define FELLOWNUMERICVERSION "0.5.6.$WCREV$"

#endif
