#pragma once

bool draw_fps_font[12][5][4] = 
{ false,false,true,false,  /* 1 */
  false,false,true,false,
  false,false,true,false,
  false,false,true,false,
  false,false,true,false,
  true,true,true,false,  /* 2 */
  false,false,true,false,
  true,true,true,false,
  true,false,false,false,
  true,true,true,false,
  true,true,true,false,  /* 3 */
  false,false,true,false,
  true,true,true,false,
  false,false,true,false,
  true,true,true,false,
  true,false,true,false,  /* 4 */
  true,false,true,false,
  true,true,true,false,
  false,false,true,false,
  false,false,true,false,
  true,true,true,false,  /* 5 */
  true,false,false,false,
  true,true,true,false,
  false,false,true,false,
  true,true,true,false,
  true,true,true,false,  /* 6 */
  true,false,false,false,
  true,true,true,false,
  true,false,true,false,
  true,true,true,false,
  true,true,true,false,  /* 7 */
  false,false,true,false,
  false,false,true,false,
  false,false,true,false,
  false,false,true,false,
  true,true,true,false,  /* 8 */
  true,false,true,false,
  true,true,true,false,
  true,false,true,false,
  true,true,true,false,
  true,true,true,false,  /* 9 */
  true,false,true,false,
  true,true,true,false,
  false,false,true,false,
  true,true,true,false,
  true,true,true,false,  /* 0 */
  true,false,true,false,
  true,false,true,false,
  true,false,true,false,
  true,true,true,false,
  false,false,false,false,  /* % */
  true,false,false,true,  
  false,false,true,false,
  false,true,false,false,
  true,false,false,true,  
  false,false,false,false,  /* space */
  false,false,false,false,
  false,false,false,false,
  false,false,false,false,
  false,false,false,false};
