%ifndef DATA_BLIT_INC
%define DATA_BLIT_INC

;==============================================================================
; Includes data declared in the C blit module
;==============================================================================

CDATAEXTERN blit_minterm
CDATAEXTERN blit_a_shift_asc
CDATAEXTERN blit_a_shift_desc
CDATAEXTERN blit_b_shift_asc
CDATAEXTERN blit_b_shift_desc
CDATAEXTERN blit_desc
CDATAEXTERN blit_asm_minterm
CDATAEXTERN blit_min_functable
CDATAEXTERN blitend
CDATAEXTERN bltzero
CDATAEXTERN bltcon
CDATAEXTERN bltafwm
CDATAEXTERN bltalwm
CDATAEXTERN bltapt
CDATAEXTERN bltbpt
CDATAEXTERN bltcpt
CDATAEXTERN bltdpt
CDATAEXTERN bltamod
CDATAEXTERN bltbmod
CDATAEXTERN bltcmod
CDATAEXTERN bltdmod
CDATAEXTERN bltadat
CDATAEXTERN bltbdat
CDATAEXTERN bltcdat
CDATAEXTERN bltbdat_original
CDATAEXTERN bltlinesulsudaul
CDATAEXTERN blitter_fast
CDATAEXTERN blit_width
CDATAEXTERN blit_height
CDATAEXTERN blit_started
CDATAEXTERN blitterdmawaiting
CDATAEXTERN blitter_ECS
CDATAEXTERN blitter_operation_log

%endif

