%ifndef DATA_BLIT_INC
%define DATA_BLIT_INC

;==============================================================================
; Includes data declared in the C blit module
;==============================================================================

CDATAEXTERN blit_leftoverA
CDATAEXTERN blit_leftoverB
CDATAEXTERN blit_cycletab
CDATAEXTERN bltdesc
CDATAEXTERN blit_min_functable
CDATAEXTERN blitend

CDATAEXTERN bltzero
CDATAEXTERN bltcon
CDATAEXTERN bltafwm
CDATAEXTERN bltalwm
CDATAEXTERN bltapt
CDATAEXTERN bltbpt
CDATAEXTERN bltcpt
CDATAEXTERN bltdpt
CDATAEXTERN bltamod
CDATAEXTERN bltbmod
CDATAEXTERN bltcmod
CDATAEXTERN bltdmod
CDATAEXTERN bltadat
CDATAEXTERN bltbdat
CDATAEXTERN bltcdat
CDATAEXTERN bltminterm
CDATAEXTERN blitterstatus
CDATAEXTERN bltadatoriginal
CDATAEXTERN bltbdatoriginal
CDATAEXTERN bltbdatline
CDATAEXTERN fillincfc0
CDATAEXTERN fillincfc1
CDATAEXTERN fillexcfc0
CDATAEXTERN fillexcfc1
CDATAEXTERN fillincfc0after
CDATAEXTERN fillincfc1after
CDATAEXTERN fillexcfc0after
CDATAEXTERN fillexcfc1after
CDATAEXTERN bltlineheight
CDATAEXTERN bltlinepointflag
CDATAEXTERN bltfillbltconsave
CDATAEXTERN bltlinedecision

CDATAEXTERN blittermodes
CDATAEXTERN blitterfillmodes
CDATAEXTERN bltlinesudsulaul

CDATAEXTERN blitter_fast

CDATAEXTERN linelength
CDATAEXTERN linenum
CDATAEXTERN linecount
CDATAEXTERN blitterdmawaiting
CDATAEXTERN blitter_ECS
CDATAEXTERN blitter_operation_log

%endif

