%ifndef DATA_SPRITE_INC
%define DATA_SPRITE_INC

;==============================================================================
; Includes data declared in the C sprite module
;==============================================================================

CDATAEXTERN sprite_deco01
CDATAEXTERN sprite_deco02
CDATAEXTERN sprite_deco03
CDATAEXTERN sprite_deco04
CDATAEXTERN sprite_deco11
CDATAEXTERN sprite_deco12
CDATAEXTERN sprite_deco21
CDATAEXTERN sprite_deco22
CDATAEXTERN sprite_deco31
CDATAEXTERN sprite_deco32
CDATAEXTERN sprite4_0
CDATAEXTERN sprite4_1


CDATAEXTERN sprite
CDATAEXTERN sprites_online
CDATAEXTERN sprite_online
CDATAEXTERN sprite_state
CDATAEXTERN sprite_state_old
CDATAEXTERN sprite_16col
CDATAEXTERN sprite_ddf_kill
CDATAEXTERN sprite_translate
CDATAEXTERN sprite_delay
CDATAEXTERN sprpt
CDATAEXTERN sprx
CDATAEXTERN spry
CDATAEXTERN sprly
CDATAEXTERN spratt
CDATAEXTERN sprdat


CDATAEXTERN sprite_write_buffer
CDATAEXTERN sprite_write_next
CDATAEXTERN sprite_write_real


%endif