//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GUI_general.rc
//
#define IDS_STRING_CLASSNAME_MAIN       1
#define IDS_APP_TITLE                   2
#define IDS_FIRSTDAY                    3
#define IDS_STRING4                     4
#define IDS_STRING5                     5
#define IDS_STRING6                     6
#define IDS_STRING7                     7
#define IDS_STRING8                     8
#define IDD_MAIN                        101
#define IDR_FELLOW_GUI_MENU             102
#define IDB_FELLOW                      106
#define IDD_CPU                         107
#define IDB_SLPASH                      107
#define IDD_SPLASH                      109
#define IDD_FLOPPY                      110
#define IDD_BLITTER                     111
#define IDD_SOUND                       112
#define IDD_FILESYSTEM                  113
#define IDD_HARDFILE                    114
#define IDD_MEMORY                      115
#define IDD_GAMEPORT                    116
#define IDD_VARIOUS                     117
#define IDD_FILESYSTEM_ADD              119
#define IDD_HARDFILE_ADD                120
#define IDD_SCREEN                      121
#define IDD_DISPLAY                     122
#define IDD_ABOUT                       125
#define IDI_ICON_WINFELLOW              128
#define IDD_NEW_MAIN                    129
#define IDD_NEW_FLOPPY                  130
#define IDB_POWER_LED_ON                137
#define IDB_DISKDRIVE_LED_ON            138
#define IDB_POWER_LED_OFF               139
#define IDB_DISKDRIVE_LED_OFF           140
#define IDB_DISKDRIVE_LED_DISABLED      141
#define IDD_HARDFILE_CREATE             150
#define IDB_WINFELLOW_LOGO              154
#define IDD_DIALOG1                     155
#define IDI_ICON_DISPLAY                159
#define IDI_ICON_SOUND                  167
#define IDI_ICON_FLOPPY                 168
#define IDI_ICON_HARDFILE               169
#define IDI_ICON_FILESYSTEM             170
#define IDI_ICON_CPU                    171
#define IDD_DEBUGGER                    181
#define IDD_FLOPPY_ADF_CREATE           182
#define IDD_PRESETS                     183
#define IDC_CONFIGURATION               1003
#define IDC_SLIDER_CPU_SPEED            1007
#define IDC_START_EMULATION             1008
#define IDC_QUIT_EMULATOR               1009
#define IDC_RADIO_68000                 1010
#define IDC_HARD_RESET                  1011
#define IDC_RADIO_68010                 1012
#define IDC_RADIO_68020                 1013
#define IDC_RADIO_68030                 1014
#define IDC_RADIO_68EC20                1015
#define IDC_RADIO_68EC30                1016
#define IDC_EDIT_FLOPPY_ADF_CREATE_FILENAME 1017
#define IDC_EDIT_FILESYSTEM_ADD_ROOTPATH 1018
#define IDC_EDIT_FLOPPY_ADF_CREATE_VOLUME 1019
#define IDC_EDIT_FILESYSTEM_ADD_VOLUMENAME 1020
#define IDC_RADIO_68040                 1021
#define IDC_EDIT3                       1022
#define IDC_EDIT_HARDFILE_ADD_SURFACES  1023
#define IDC_RADIO_68060                 1024
#define IDC_EDIT4                       1025
#define IDC_EDIT_HARDFILE_ADD_RESERVED  1026
#define IDC_RADIO_68EC40                1027
#define IDC_BTN_STEP1                   1028
#define IDC_FLOPPY_ADF_CREATE_SELECT    1028
#define IDC_BUTTON_FILESYSTEM_ADD_DIRDIALOG 1029
#define IDC_BUTTON_HARDFILE_CREATE      1030
#define IDC_RADIO_68EC60                1031
#define IDC_BUTTON_DF1_SWAP             1032
#define IDC_BUTTON2                     1033
#define IDC_BTN_STEP_OVER               1033
#define IDC_BUTTON_KEYFILE_FILEDIALOG   1034
#define IDC_CHECK_DF0_ENABLED           1042
#define IDC_BUTTON_DF0_FILEDIALOG       1043
#define IDC_BUTTON_DF1_FILEDIALOG       1044
#define IDC_EDIT_DF0_IMAGENAME          1045
#define IDC_EDIT_DF1_IMAGENAME          1046
#define IDC_EDIT_DF2_IMAGENAME          1047
#define IDC_EDIT_DF3_IMAGENAME          1048
#define IDC_CHECK_DF1_READONLY          1049
#define IDC_CHECK_DF2_READONLY          1050
#define IDC_CHECK_DF3_READONLY          1051
#define IDC_COMBO_CHIP                  1052
#define IDC_BUTTON_DF0_CREATE           1052
#define IDC_CHECK_DF0_READONLY          1053
#define IDC_COMBO_FAST                  1054
#define IDC_BUTTON_DF1_CREATE           1054
#define IDC_BUTTON_DF0_EJECT            1055
#define IDC_EDIT_KICKSTART              1056
#define IDC_BUTTON_DF1_EJECT            1057
#define IDC_EDIT_KICKSTART_EXT          1057
#define IDC_EDIT_KEYFILE                1058
#define IDC_BUTTON_DF2_CREATE           1058
#define IDC_BUTTON_DF2_EJECT            1059
#define IDC_BUTTON_KICKSTART_FILEDIALOG 1060
#define IDC_BUTTON_DF3_CREATE           1060
#define IDC_CHECK_SOUND_WAV             1061
#define IDC_BUTTON_KICKSTART_EXT_FILEDIALOG 1061
#define IDC_COMBO_GAMEPORT1             1062
#define IDC_CHECK_VARIOUS_SPEED         1063
#define IDC_CHECK_HARDFILE_ENABLE       1065
#define IDC_STATIC_HARDFILE_ADD_UNIT    1067
#define IDC_EDIT_HARDFILE_ADD_FILENAME  1068
#define IDC_EDIT_HARDFILE_ADD_SECTORS   1069
#define IDC_BUTTON_HARDFILE_ADD_FILEDIALOG 1070
#define IDC_COMBO_SCREEN_RESOLUTION     1071
#define IDC_EDIT_HARDFILE_ADD_BYTES_PER_SECTOR 1072
#define IDC_RADIO_BLITTER_OCS           1073
#define IDC_RADIO_BLITTER_ECS           1075
#define IDC_TAB_CONFIG                  1076
#define IDC_ANIMATE1                    1077
#define IDC_TAB1                        1080
#define IDC_EDIT_DF0_IMAGENAME_MAIN     1081
#define IDC_EDIT_DF1_IMAGENAME_MAIN     1082
#define IDC_EDIT_DF2_IMAGENAME_MAIN     1083
#define IDC_EDIT_DF3_IMAGENAME_MAIN     1084
#define IDC_BUTTON_DF0_FILEDIALOG_MAIN  1085
#define IDC_BUTTON_DF0_EJECT_MAIN       1086
#define IDC_BUTTON_DF1_EJECT_MAIN       1087
#define IDC_BUTTON_DF1_FILEDIALOG_MAIN  1088
#define IDC_BUTTON_DF2_EJECT_MAIN       1089
#define IDC_BUTTON_DF2_FILEDIALOG_MAIN  1090
#define IDC_BUTTON_DF3_EJECT_MAIN       1091
#define IDC_BUTTON_DF3_FILEDIALOG_MAIN  1092
#define IDC_IMAGE_DF3_LED_MAIN          1093
#define IDC_IMAGE_DF2_LED_MAIN          1094
#define IDC_IMAGE_DF1_LED_MAIN          1095
#define IDC_IMAGE_DF0_LED_MAIN          1096
#define IDC_BUTTON_DF3_EJECT            1097
#define IDC_LABEL_FLOPPY_ADF_CREATE_VOLUME 1098
#define IDC_RADIO_BLITTER_NORMAL        1098
#define IDC_RADIO_BLITTER_IMMEDIATE     1099
#define IDC_IMAGE_POWER_LED_MAIN        1100
#define IDC_STATIC_LINK                 1101
#define IDC_CREATE_HARDFILE_SIZE        1102
#define IDC_CREATE_HARDFILE_NAME        1103
#define IDC_GAMEPORT0_UP                1104
#define IDC_GAMEPORT0_DOWN              1105
#define IDC_GAMEPORT0_LEFT              1106
#define IDC_GAMEPORT0_RIGHT             1107
#define IDC_GAMEPORT0_FIRE0             1108
#define IDC_GAMEPORT0_FIRE1             1109
#define IDC_GAMEPORT1_UP                1110
#define IDC_GAMEPORT0_FIRE2             1111
#define IDC_GAMEPORT0_AUTOFIRE0         1112
#define IDC_GAMEPORT1_RIGHT             1113
#define IDC_GAMEPORT1_LEFT              1114
#define IDC_GAMEPORT1_FIRE0             1115
#define IDC_GAMEPORT1_FIRE1             1116
#define IDC_GAMEPORT1_DOWN              1117
#define IDC_GAMEPORT1_FIRE2             1118
#define IDC_GAMEPORT1_AUTOFIRE0         1119
#define IDC_SLIDER_SCREEN_AREA          1120
#define IDC_GAMEPORT0_FIRE3             1121
#define IDC_GAMEPORT0_AUTOFIRE1         1122
#define IDC_GAMEPORT1_FIRE3             1123
#define IDC_GAMEPORT1_AUTOFIRE1         1124
#define IDC_CHECK_HORIZONTAL_SCALE      1125
#define IDC_SLIDER_FRAME_SKIPPING       1127
#define IDC_CHECK_MULTIPLE_BUFFERS      1128
#define IDC_CHECK_SOUND_NOTIFICATION    1129
#define IDC_SLIDER_SOUND_BUFFER_LENGTH  1130
#define IDC_STATIC_BUFFER_LENGTH        1131
#define IDC_COMBO_COLOR_BITS            1132
#define IDC_STATIC_SOUND_VOLUME_0       1132
#define IDC_STATIC_SOUND_VOLUME         1132
#define IDC_COMBO_DISPLAY_DRIVER        1133
#define IDC_STATIC_SCREEN_AREA          1134
#define IDC_STATIC_FRAME_SKIPPING       1135
#define IDC_BUTTON_HARDFILE_CREATE_FILEDIALOG 1136
#define IDC_STATIC_VERSION              1137
#define IDC_STATIC_ABOUT_VERSION        1138
#define IDC_LST_REGISTERS               1140
#define IDC_LST_INFO                    1141
#define IDC_LST_INSTRUCTIONS            1142
#define IDC_SLIDER_SOUND_VOLUME         1143
#define IDC_CHECK_FLOPPY_ADF_CREATE_FORMAT 1144
#define IDC_EDIT_PRESETS_ROMSEARCHPATH  1145
#define IDC_BUTTON_PRESETS_ROMSEARCHPATH 1146
#define IDC_BUTTON_PRESETS_APPLY        1147
#define IDC_LABEL_PRESETS_ROM           1148
#define IDC_LABEL_PRESETS_ROMLOCATION   1149
#define IDC_LABEL_PRESETS_CHIPSET       1150
#define IDC_LABEL_PRESETS_CPU           1151
#define IDC_LABEL_PRESETS_CHIPRAM       1152
#define IDC_LABEL_PRESETS_FASTRAM       1153
#define IDC_LABEL_PRESETS_BOGORAM       1154
#define IDC_LABEL_PRESETS_ROM_LABEL     1155
#define IDC_LABEL_PRESETS_ROM_LOCATION_LABEL 1156
#define IDC_LABEL_PRESETS_CHIPSET_LABEL 1157
#define IDC_LABEL_PRESETS_CPU_LABEL     1158
#define IDC_LABEL_PRESETS_CHIPRAM_LABEL 1159
#define IDC_LABEL_PRESETS_MODEL         1160
#define IDC_LABEL_PRESETS_FASTRAM_LABEL 1161
#define IDC_LABEL_PRESETS_BOGORAM_LABEL 1162
#define IDC_CHECK_GRAPHICS_DEINTERLACE  1163
#define IDC_DISPLAYSCALE_COMBO          1164
#define IDC_COMBO_DISPLAYSCALE          1164
#define IDC_COMBO1                      1167
#define IDC_COMBO_BORDER                1167
#define IDC_TREE1                       1168
#define IDC_HARDFILE_TREE               1168
#define IDC_TREE_HARDFILES              1168
#define IDC_CHECK_HARDFILE_ADD_READONLY 1169
#define IDC_EDIT_PREFIX_FILESYSTEMS     1170
#define IDC_BUTTON_DF2_SWAP             2000
#define IDC_BTN_RUN                     2001
#define IDC_BUTTON_DF2_FILEDIALOG       2002
#define IDC_BUTTON_DF3_SWAP             2003
#define IDC_BTN_BREAK                   2004
#define IDC_BUTTON_DF3_FILEDIALOG       2005
#define IDC_BTN_DUMPCHIP                2005
#define IDC_BUTTON_TURBO_LOAD           2006
#define IDC_DEBUG_RIP                   2006
#define IDC_BTN_MODRIP                  2006
#define IDC_CHECK_SOUND_EMULATE         2007
#define IDC_CHECK_FILESYSTEM_ADD_READONLY 2008
#define IDC_CHECK_VARIOUS_RTC           2008
#define IDC_CHECK_VARIOUS_LED           2009
#define IDC_CHECK_CREATE_HARDFILE_MEGABYTES 2010
#define IDC_CHECK_FULLSCREEN            2011
#define IDC_CHECK_FLOPPY_ADF_CREATE_BOOTABLE 2012
#define IDC_RADIO_LINE_FILL_SOLID       2013
#define IDC_CHECK_DF1_ENABLED           2014
#define IDC_RADIO_SOUND_NO_EMULATION    2015
#define IDC_RADIO_SCREEN_HSCALE_SINGLE  2016
#define IDC_CHECK_AUTOCONFIG_DISABLE    2017
#define IDC_CHECK_FLOPPY_ADF_CREATE_FFS 2019
#define IDC_RADIO_LINE_FILL_SCANLINES   2020
#define IDC_CHECK_DF2_ENABLED           2021
#define IDC_RADIO_SOUND_PLAY            2022
#define IDC_CHECK_AUTOMOUNT_FILESYSTEMS 2024
#define IDC_CHECK_DF3_ENABLED           2028
#define IDC_RADIO_SOUND_SILENT_EMULATION 2029
#define IDC_RADIO_SOUND_31300           2031
#define IDC_COMBO_PRESETS_MODEL         2032
#define IDC_RADIO_SOUND_44100           2034
#define IDC_RADIO_DISPLAYSIZE_1X        2035
#define IDC_RADIO_SOUND_22050           2038
#define IDC_COMBO_GAMEPORT2             2039
#define IDC_COMBO_BOGO                  2044
#define IDC_RADIO_SOUND_15650           2045
#define IDC_COMBO_SCREEN_FRAMESKIP      2046
#define IDC_RADIO_DISPLAYSIZE_2X        2047
#define IDC_RADIO_SOUND_STEREO          2049
#define IDC_RADIO_SOUND_MONO            2053
#define IDC_RADIO_SOUND_16BITS          2057
#define IDC_RADIO_SOUND_8BITS           2059
#define IDC_RADIO_SOUND_FILTER_ORIGINAL 2061
#define IDC_RADIO_SOUND_FILTER_ALWAYS   2064
#define IDC_LIST_FILESYSTEMS            2065
#define IDC_BUTTON_ADD_FILESYSTEM       2067
#define IDC_RADIO_SOUND_FILTER_NEVER    2068
#define IDC_BUTTON_FILESYSTEM_ADD       2069
#define IDC_BUTTON_ADD_HARDFILE         2070
#define IDC_BUTTON_HARDFILE_ADD         2071
#define IDC_BUTTON_FILESYSTEM_EDIT      2072
#define IDC_BUTTON_REMOVE_HARDFILE      2073
#define IDC_BUTTON_HARDFILE_REMOVE      2074
#define IDC_BUTTON_REMOVE_FILESYSTEM    2075
#define IDC_BUTTON_FILESYSTEM_REMOVE    2076
#define IDC_BUTTON_HARDFILE_EDIT        2077
#define IDC_CHECK_FAST_DMA              2078
#define ID_FILE_QUIT                    40001
#define ID_HELP_ABOUT                   40002
#define ID_DEBUGGER_START               40003
#define ID_FILE_OPENCONFIGURATION       40004
#define ID_FILE_SAVECONFIGURATION       40005
#define ID_FILE_SAVECONFIGURATIONAS     40006
#define ID_FILE_HISTORYCONFIGURATION0   40007
#define ID_FILE_HISTORYCONFIGURATION1   40008
#define ID_FILE_HISTORYCONFIGURATION2   40009
#define ID_FILE_HISTORYCONFIGURATION3   40010
#define ID_OPTIONS_EMULATIONSPEED_FASTESTPOSSIBLENOSOUND 40010
#define ID_OPTIONS_MULTIPLE_GRAPHICAL_BUFFERS 40011
#define ID_FILE_LOADSTATEFILE           40011
#define ID_FILE_SAVESTATEFILE           40012
#define ID_Menu                         40013
#define ID_FILE_SAVESTATEFILE40014      40014
#define ID_FILE_LOAD_STATE              40015
#define ID_FILE_SAVESTATE               40016
#define ID_FILE_SAVE_STATE              40017
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        188
#define _APS_NEXT_COMMAND_VALUE         40018
#define _APS_NEXT_CONTROL_VALUE         1171
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
