%ifndef DATA_COPPER_INC
%define DATA_COPPER_INC

;==============================================================================
; Includes data declared in the C copper module
;==============================================================================

CDATAEXTERN copper_next
CDATAEXTERN copper_dma
CDATAEXTERN copper_suspended_wait
CDATAEXTERN copper_ptr
CDATAEXTERN copcon
CDATAEXTERN cop1lc
CDATAEXTERN cop2lc
CDATAEXTERN copper_cycletable
CDATAEXTERN copper_ytable

%endif
