//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GUI_general.rc
//
#define IDS_STRING_CLASSNAME_MAIN       1
#define IDS_APP_TITLE                   2
#define IDS_FIRSTDAY                    3
#define IDS_STRING4                     4
#define IDS_STRING5                     5
#define IDS_STRING6                     6
#define IDS_STRING7                     7
#define IDS_STRING8                     8
#define IDD_MAIN                        101
#define IDR_FELLOW_GUI_MENU             102
#define IDB_FELLOW                      106
#define IDD_CPU                         107
#define IDB_SLPASH                      107
#define IDD_SPLASH                      109
#define IDD_FLOPPY                      110
#define IDD_BLITTER                     111
#define IDD_SOUND                       112
#define IDD_FILESYSTEM                  113
#define IDD_HARDFILE                    114
#define IDD_MEMORY                      115
#define IDD_GAMEPORT                    116
#define IDD_VARIOUS                     117
#define IDD_FILESYSTEM_ADD              119
#define IDD_HARDFILE_ADD                120
#define IDD_SCREEN                      121
#define IDD_DISPLAY                     122
#define IDD_ABOUT                       125
#define IDI_ICON_WINFELLOW              128
#define IDD_NEW_MAIN                    129
#define IDD_NEW_FLOPPY                  130
#define IDB_POWER_LED_ON                137
#define IDB_DISKDRIVE_LED_ON            138
#define IDB_POWER_LED_OFF               139
#define IDB_DISKDRIVE_LED_OFF           140
#define IDB_DISKDRIVE_LED_DISABLED      141
#define IDD_HARDFILE_CREATE             150
#define IDB_WINFELLOW_LOGO              154
#define IDD_DIALOG1                     155
#define IDC_CONFIGURATION               1003
#define IDC_SLIDER_CPU_SPEED            1007
#define IDC_START_EMULATION             1008
#define IDC_QUIT_EMULATOR               1009
#define IDC_RADIO_68000                 1010
#define IDC_HARD_RESET                  1010
#define IDC_RADIO_68010                 1011
#define IDC_RADIO_68020                 1012
#define IDC_RADIO_68030                 1013
#define IDC_RADIO_68EC20                1014
#define IDC_RADIO_68EC30                1015
#define IDC_EDIT1                       1015
#define IDC_EDIT_FILESYSTEM_ADD_ROOTPATH 1015
#define IDC_EDIT2                       1016
#define IDC_EDIT_FILESYSTEM_ADD_VOLUMENAME 1016
#define IDC_EDIT3                       1017
#define IDC_EDIT_HARDFILE_ADD_SURFACES  1017
#define IDC_EDIT4                       1018
#define IDC_EDIT_HARDFILE_ADD_RESERVED  1018
#define IDC_BUTTON1                     1019
#define IDC_BUTTON_FILESYSTEM_ADD_DIRDIALOG 1019
#define IDC_BUTTON_HARDFILE_CREATE      1019
#define IDC_BUTTON2                     1020
#define IDC_BUTTON_KEYFILE_FILEDIALOG   1020
#define IDC_BUTTON3                     1021
#define IDC_BUTTON_DF2_FILEDIALOG       1021
#define IDC_BUTTON4                     1022
#define IDC_BUTTON_DF3_FILEDIALOG       1022
#define IDC_CHECK1                      1023
#define IDC_CHECK_FILESYSTEM_ADD_READONLY 1023
#define IDC_CHECK_VARIOUS_LED           1023
#define IDC_CHECK_CREATE_HARDFILE_MEGABYTES 1023
#define IDC_CHECK2                      1024
#define IDC_RADIO1                      1024
#define IDC_CHECK_DF1_ENABLED           1024
#define IDC_RADIO_SOUND_NO_EMULATION    1024
#define IDC_RADIO_SCREEN_HSCALE_SINGLE  1024
#define IDC_CHECK_AUTOCONFIG_DISABLE    1024
#define IDC_CHECK3                      1025
#define IDC_RADIO2                      1025
#define IDC_CHECK_DF2_ENABLED           1025
#define IDC_RADIO_SOUND_PLAY            1025
#define IDC_RADIO_SCREEN_HSCALE_DOUBLE  1025
#define IDC_CHECK_AUTOMOUNT_FILESYSTEMS 1025
#define IDC_CHECK4                      1026
#define IDC_RADIO3                      1026
#define IDC_CHECK_DF3_ENABLED           1026
#define IDC_RADIO_SOUND_SILENT_EMULATION 1026
#define IDC_RADIO4                      1027
#define IDC_RADIO_SOUND_31300           1027
#define IDC_COMBO1                      1028
#define IDC_RADIO5                      1028
#define IDC_RADIO_SOUND_44100           1028
#define IDC_COMBO2                      1029
#define IDC_RADIO6                      1029
#define IDC_RADIO_SOUND_22050           1029
#define IDC_COMBO_GAMEPORT2             1029
#define IDC_RADIO_SCREEN_VSCALE_SINGLE  1029
#define IDC_COMBO3                      1030
#define IDC_RADIO7                      1030
#define IDC_COMBO_BOGO                  1030
#define IDC_RADIO_SOUND_15650           1030
#define IDC_COMBO_SCREEN_FRAMESKIP      1030
#define IDC_RADIO8                      1031
#define IDC_RADIO_SOUND_STEREO          1031
#define IDC_RADIO_SCREEN_VSCALE_DOUBLE  1031
#define IDC_RADIO9                      1032
#define IDC_RADIO_SOUND_MONO            1032
#define IDC_RADIO_SCREEN_VSCALE_SCANLINES 1032
#define IDC_RADIO10                     1033
#define IDC_RADIO_SOUND_16BITS          1033
#define IDC_RADIO11                     1034
#define IDC_RADIO_SOUND_8BITS           1034
#define IDC_RADIO12                     1035
#define IDC_RADIO_SOUND_FILTER_ORIGINAL 1035
#define IDC_RADIO13                     1036
#define IDC_LIST1                       1036
#define IDC_RADIO_SOUND_FILTER_ALWAYS   1036
#define IDC_LIST_FILESYSTEMS            1036
#define IDC_RADIO14                     1037
#define IDC_BUTTON_ADD_FILESYSTEM       1037
#define IDC_RADIO_SOUND_FILTER_NEVER    1037
#define IDC_BUTTON_FILESYSTEM_ADD       1037
#define IDC_BUTTON_ADD_HARDFILE         1038
#define IDC_BUTTON_HARDFILE_ADD         1038
#define IDC_BUTTON_FILESYSTEM_EDIT      1038
#define IDC_BUTTON_REMOVE_HARDFILE      1039
#define IDC_BUTTON_HARDFILE_REMOVE      1039
#define IDC_BUTTON_REMOVE_FILESYSTEM    1040
#define IDC_BUTTON_FILESYSTEM_REMOVE    1040
#define IDC_BUTTON_HARDFILE_EDIT        1040
#define IDC_CHECK_FAST_DMA              1041
#define IDC_CHECK_DF0_ENABLED           1042
#define IDC_BUTTON_DF0_FILEDIALOG       1043
#define IDC_BUTTON_DF1_FILEDIALOG       1044
#define IDC_EDIT_DF0_IMAGENAME          1045
#define IDC_EDIT_DF1_IMAGENAME          1046
#define IDC_EDIT_DF2_IMAGENAME          1047
#define IDC_EDIT_DF3_IMAGENAME          1048
#define IDC_CHECK_DF1_READONLY          1049
#define IDC_CHECK_DF2_READONLY          1050
#define IDC_CHECK_DF3_READONLY          1051
#define IDC_COMBO_CHIP                  1052
#define IDC_CHECK_DF0_READONLY          1052
#define IDC_COMBO_FAST                  1053
#define IDC_BUTTON_DF0_EJECT            1053
#define IDC_EDIT_KICKSTART              1054
#define IDC_BUTTON_DF1_EJECT            1054
#define IDC_EDIT_KEYFILE                1055
#define IDC_BUTTON_DF2_EJECT            1055
#define IDC_BUTTON_KICKSTART_FILEDIALOG 1056
#define IDC_BUTTON_DF3_EJECT            1056
#define IDC_RADIO_BLITTER_NORMAL        1057
#define IDC_RADIO_BLITTER_IMMEDIATE     1058
#define IDC_RADIO_BLITTER_OCS           1059
#define IDC_RADIO_BLITTER_ECS           1060
#define IDC_CHECK_SOUND_WAV             1061
#define IDC_COMBO_GAMEPORT1             1062
#define IDC_CHECK_VARIOUS_SPEED         1063
#define IDC_LIST_HARDFILES              1064
#define IDC_CHECK_HARDFILE_ENABLE       1065
#define IDC_STATIC_HARDFILE_ADD_UNIT    1067
#define IDC_EDIT_HARDFILE_ADD_FILENAME  1068
#define IDC_EDIT_HARDFILE_ADD_SECTORS   1069
#define IDC_BUTTON_HARDFILE_ADD_FILEDIALOG 1070
#define IDC_COMBO_SCREEN_RESOLUTION     1071
#define IDC_EDIT_HARDFILE_ADD_BYTES_PER_SECTOR 1071
#define IDC_CHECK_SCREEN_VSCALE_INTERLACE 1074
#define IDC_TAB_CONFIG                  1076
#define IDC_ANIMATE1                    1077
#define IDC_TAB1                        1080
#define IDC_EDIT_DF0_IMAGENAME_MAIN     1081
#define IDC_EDIT_DF1_IMAGENAME_MAIN     1082
#define IDC_EDIT_DF2_IMAGENAME_MAIN     1083
#define IDC_EDIT_DF3_IMAGENAME_MAIN     1084
#define IDC_BUTTON_DF0_FILEDIALOG_MAIN  1085
#define IDC_BUTTON_DF0_EJECT_MAIN       1086
#define IDC_BUTTON_DF1_EJECT_MAIN       1087
#define IDC_BUTTON_DF1_FILEDIALOG_MAIN  1088
#define IDC_BUTTON_DF2_EJECT_MAIN       1089
#define IDC_BUTTON_DF2_FILEDIALOG_MAIN  1090
#define IDC_BUTTON_DF3_EJECT_MAIN       1091
#define IDC_BUTTON_DF3_FILEDIALOG_MAIN  1092
#define IDC_IMAGE_DF3_LED_MAIN          1093
#define IDC_IMAGE_DF2_LED_MAIN          1094
#define IDC_IMAGE_DF1_LED_MAIN          1095
#define IDC_IMAGE_DF0_LED_MAIN          1096
#define IDC_IMAGE_POWER_LED_MAIN        1097
#define IDC_STATIC_LINK                 1098
#define IDC_CREATE_HARDFILE_SIZE        1100
#define IDC_CREATE_HARDFILE_NAME        1106
#define IDC_GAMEPORT0_UP                1109
#define IDC_GAMEPORT0_DOWN              1110
#define IDC_GAMEPORT0_LEFT              1111
#define IDC_GAMEPORT0_RIGHT             1112
#define IDC_GAMEPORT0_FIRE0             1113
#define IDC_GAMEPORT0_FIRE1             1114
#define IDC_GAMEPORT1_UP                1115
#define IDC_GAMEPORT1_RIGHT             1117
#define IDC_GAMEPORT1_LEFT              1118
#define IDC_GAMEPORT1_FIRE0             1119
#define IDC_GAMEPORT1_FIRE1             1120
#define IDC_GAMEPORT1_DOWN              1121
#define IDC_SLIDER1                     1123
#define IDC_COMBO5                      1124
#define IDC_CHECK5                      1125
#define IDC_SLIDER2                     1127
#define IDC_CHECK7                      1128
#define IDC_CHECK_SOUND_NOTIFICATION    1129
#define IDC_SLIDER_SOUND_BUFFER_LENGTH  1130
#define IDC_STATIC_BUFFER_LENGTH        1131
#define ID_FILE_QUIT                    40001
#define ID_HELP_ABOUT                   40002
#define ID_FILE_OPENCONFIGURATION       40004
#define ID_FILE_SAVECONFIGURATION       40005
#define ID_FILE_SAVECONFIGURATIONAS     40006
#define ID_FILE_HISTORYCONFIGURATION0   40007
#define ID_FILE_HISTORYCONFIGURATION1   40008
#define ID_FILE_HISTORYCONFIGURATION2   40009
#define ID_FILE_HISTORYCONFIGURATION3   40010
#define ID_OPTIONS_EMULATIONSPEED_FASTESTPOSSIBLENOSOUND 40010
#define ID_OPTIONS_MULTIPLE_GRAPHICAL_BUFFERS 40011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         40011
#define _APS_NEXT_CONTROL_VALUE         1132
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
