%ifndef DATA_BUS_INC
%define DATA_BUS_INC

;==============================================================================
; Includes data declared in the C bus module
;==============================================================================

CDATAEXTERN debugging
CDATAEXTERN curcycle
CDATAEXTERN bus_cycle_to_ypos
CDATAEXTERN bus_cycle_to_xpos
CDATAEXTERN eol_next
CDATAEXTERN eof_next
CDATAEXTERN lvl2_next
CDATAEXTERN lvl2_ptr  
CDATAEXTERN lvl3_next 
CDATAEXTERN lvl3_ptr  
CDATAEXTERN lvl4_next 
CDATAEXTERN lvl4_ptr  
CDATAEXTERN lvl5_next 
CDATAEXTERN lvl5_ptr  
CDATAEXTERN lvl6_next 
CDATAEXTERN lvl6_ptr  
CDATAEXTERN lvl7_next    
CDATAEXTERN lvl7_ptr     

%endif


