%ifndef DATA_SOUND_INC
%define DATA_SOUND_INC

;==============================================================================
; Includes data declared in the C sound module
;==============================================================================

CDATAEXTERN audioodd
CDATAEXTERN audiocounter
CDATAEXTERN sound_filter
CDATAEXTERN sound_left
CDATAEXTERN sound_right
CDATAEXTERN audpt
CDATAEXTERN audptw
CDATAEXTERN auddat
CDATAEXTERN auddatw
CDATAEXTERN audlen
CDATAEXTERN audlenw
CDATAEXTERN audvol
CDATAEXTERN audvolw
CDATAEXTERN audpercounter
CDATAEXTERN audstate
CDATAEXTERN audper
CDATAEXTERN periodtable
CDATAEXTERN volumes
CDATAEXTERN audiodmaconmask
CDATAEXTERN audioirqmask
CDATAEXTERN sound_scale
CDATAEXTERN sound_buffer_sample_count

%endif
